### ISSUE TITLE
Install error 

### ISSUE THREAD

**Issue by ReGizmoAaron** [magespecialist/m2-MSP_Security_Suite#1]
I have just tried installing it using your instructions and get the following error message: 

`Module 'MSP_UserLockout':
Upgrading data...                                                                                                                                                    
  [Zend_Db_Statement_Exception]                                                                                                                              
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'xxxxxxxx_mage437.core_config_data' doesn't exist, query was: UPDATE `core_config_data` SET `path` = ? WHERE (path='msp_securitysuite/userlockout')

  [PDOException]
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'xxxxxxxx_mage437.core_config_data' doesn't exist`

**Comment by phoenix128** [comment]
Hello @ReGizmoAaron ,
thank you for your report.

Referring to your previous email:

```
The correct table should be mgdb_core_config_data as the database has a prefix "mgdb_" as defined in "app/etc/env.php". I do not think your extension takes this into account and not sure where to update it. 

'table_prefix' => 'mgdb_',
```

It probably depends on a wrong table names prefix management.

We are setting up a test environemnt with prefixes to check it.

**Comment by phoenix128** [comment]
Issue confirmed, it depends on the tables prefix.
We are at work to fix this.

**Comment by phoenix128** [comment]
Should be fixed now.

Update your composer.json to version 1.2.17 of msp/security-suite and run:
`composer update msp/security-suite msp/twofactorauth msp/shield msp/security-suite-common`

Then run:
`php bin/magento setup:upgrade`

Please confirm it is correctly working now.

**Comment by ReGizmoAaron** [comment]
Installed successfully.

Thanks.
